name: Build and Test

on:
  push:
    paths:
      - "EnvConvert/**"
      - "EnvConvert.Tests/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "5.0.x"

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --verbosity quiet
