name: Publish to NuGet

on:
  push:

jobs:
  publish:
    name: Pack and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: EnvConvert/EnvConvert.csproj
          PACKAGE_NAME: envconvert
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
